In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [12]:
initial_dataframe=pd.read_excel('MDS- Case Study Data - Lifetime Value Prediction.xlsx')

In [13]:
initial_dataframe['GROUP']=initial_dataframe['ACQ_TRIP_TYPE']+'/'+initial_dataframe['ACQ_BOOKING_PLATFORM']+'/'+initial_dataframe['ACQ_LENGTH_OF_STAY_CATEGORY']+'/'
+initial_dataframe['ACQ_BOOKING_LEADTIME']

0           1-2 days
1           3-6 days
2           Same day
3         31-60 days
4           3-6 days
             ...
109577      3-6 days
109578      3-6 days
109579     7-30 days
109580    31-60 days
109581      Same day
Name: ACQ_BOOKING_LEADTIME, Length: 109582, dtype: object

In [14]:
initial_dataframe['LIFETIME_BEDVALUE']= initial_dataframe['LIFETIME_BEDVALUE'].fillna(initial_dataframe.groupby('GROUP')['LIFETIME_BEDVALUE'].median())

In [15]:
initial_dataframe=initial_dataframe[initial_dataframe['LIFETIME_BEDVALUE']!=0]

In [16]:
initial_dataframe[initial_dataframe['LIFETIME_BEDVALUE']==0]

Empty DataFrame
Columns: [CUSTOMER_ID, ACQ_BOOKEDDATE, ACQ_TRIP_TYPE, ACQ_BOOKING_PLATFORM, ACQ_LENGTH_OF_STAY_CATEGORY, ACQ_BEDVALUE, ACQ_BOOKING_LEADTIME, LIFETIME_BEDVALUE, GROUP]
Index: []

In [17]:
training_df=initial_dataframe

In [18]:
training_df

,CUSTOMER_ID,ACQ_BOOKEDDATE,ACQ_TRIP_TYPE,ACQ_BOOKING_PLATFORM,ACQ_LENGTH_OF_STAY_CATEGORY,ACQ_BEDVALUE,ACQ_BOOKING_LEADTIME,LIFETIME_BEDVALUE,GROUP
0,1,2018-11-22,Short Haul,DESKTOP,1-2 Nights,55.750443,1-2 days,252.502492,Short Haul/DESKTOP/1-2 Nights/
1,2,2018-10-25,Domestic,DESKTOP,1-2 Nights,202.205070,3-6 days,5315.664345,Domestic/DESKTOP/1-2 Nights/
2,3,2018-09-12,Domestic,MOBILE,1-2 Nights,132.692400,Same day,2574.514393,Domestic/MOBILE/1-2 Nights/
3,4,2018-09-17,Long Haul,DESKTOP,1-2 Nights,636.734275,31-60 days,313.337171,Long Haul/DESKTOP/1-2 Nights/
4,5,2018-11-01,Domestic,MOBILE,1-2 Nights,104.654210,3-6 days,1511.881143,Domestic/MOBILE/1-2 Nights/
...,...,...,...,...,...,...,...,...,...
109577,109578,2018-11-22,Domestic,MOBILE,3-4 Nights,732.245531,3-6 days,13876.289411,Domestic/MOBILE/3-4 Nights/
109578,109579,2018-10-23,Long Haul,MOBILE,1-2 Nights,184.474761,3-6 days,332.290163,Long Haul/MOBILE/1-2 Nights/
109579,109580,2018-10-03,Short Haul,DESKTOP,1-2 Nights,15.205975,7-30 days,3407.352069,Short Haul/DESKTOP/1-2 Nights/
109580,109581,2018-10-02,Short Haul,DESKTOP,3-4 Nights,1079.656930,31-60 days,6471.776885,Short Haul/DESKTOP/3-4 Nights/
109581,109582,2018-09-20,Domestic,MOBILE,3-4 Nights,116.243858,Same day,501.730637,Domestic/MOBILE/3-4 Nights/

In [19]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

le2 = preprocessing.LabelEncoder()
le2.fit(['Domestic', 'Short Haul', 'Long Haul'])
le2.classes_=(['Domestic', 'Short Haul', 'Long Haul'])
training_df['ACQ_TRIP_TYPE_encoded'] = le2.transform(training_df['ACQ_TRIP_TYPE'])

le3 = preprocessing.LabelEncoder()
training_df['ACQ_BOOKING_PLATFORM_encoded'] = le3.fit_transform(training_df['ACQ_BOOKING_PLATFORM'])

le4 = preprocessing.LabelEncoder()
le4.fit(['1-2 Nights', '3-4 Nights', '5-6 Nights','7+ Nights'])
le4.classes_=(['1-2 Nights', '3-4 Nights', '5-6 Nights','7+ Nights'])
training_df['ACQ_LENGTH_OF_STAY_CATEGORY_encoded'] = le4.transform(training_df['ACQ_LENGTH_OF_STAY_CATEGORY'])

le5 = preprocessing.LabelEncoder()
le5.fit(['Same day', '1-2 days', '3-6 days', '7-30 days', '31-60 days', '60+ days'])
le5.classes_=(['Same day', '1-2 days', '3-6 days', '7-30 days', '31-60 days', '60+ days'])
training_df['ACQ_BOOKING_LEADTIME_encoded'] = le5.transform(training_df['ACQ_BOOKING_LEADTIME'])

le6 = preprocessing.LabelEncoder()
training_df['GROUP_encoded'] = le6.fit_transform(training_df['GROUP'])

training_df.drop(['GROUP','ACQ_TRIP_TYPE','ACQ_LENGTH_OF_STAY_CATEGORY','ACQ_BOOKING_LEADTIME','ACQ_BOOKING_PLATFORM'],axis=1, inplace = True)

training_df

# training_df.drop(['ACQ_BOOKEDDATE'], axis=1, inplace = True)

# X = training_df.drop('LIFETIME_BEDVALUE',axis=1).values
# y = training_df['LIFETIME_BEDVALUE'].values

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

,CUSTOMER_ID,ACQ_BOOKEDDATE,ACQ_BEDVALUE,LIFETIME_BEDVALUE,ACQ_TRIP_TYPE_encoded,ACQ_BOOKING_PLATFORM_encoded,ACQ_LENGTH_OF_STAY_CATEGORY_encoded,ACQ_BOOKING_LEADTIME_encoded,GROUP_encoded
0,1,2018-11-22,55.750443,252.502492,1,0,0,1,16
1,2,2018-10-25,202.205070,5315.664345,0,0,0,2,0
2,3,2018-09-12,132.692400,2574.514393,0,1,0,0,4
3,4,2018-09-17,636.734275,313.337171,2,0,0,4,8
4,5,2018-11-01,104.654210,1511.881143,0,1,0,2,4
...,...,...,...,...,...,...,...,...,...
109577,109578,2018-11-22,732.245531,13876.289411,0,1,1,2,5
109578,109579,2018-10-23,184.474761,332.290163,2,1,0,2,12
109579,109580,2018-10-03,15.205975,3407.352069,1,0,0,3,16
109580,109581,2018-10-02,1079.656930,6471.776885,1,0,1,4,17
109581,109582,2018-09-20,116.243858,501.730637,0,1,1,0,5

In [ ]:
training_df.to_csv('fe_4.csv')